package com.noasaba.boltextension.model;

public enum SkipReason {
    NOT_PROTECTABLE,
    PROTECTION_TYPE_UNKNOWN,
    PROTECTION_TYPE_DENIED,
    BLOCK_LOCK_PERMISSION_DENIED,
    LOCK_EVENT_CANCELLED,
    NO_PROTECTION,
    OWNER_MISMATCH,
    WORLDGUARD_DENIED,
    PROTECTION_BLOCK_UNAVAILABLE,
    DUPLICATE_PROTECTION,
    TYPE_ALREADY_SET,
    TRANSFER_TARGET_SAME_AS_OWNER
}
