package com.noasaba.boltextension.model;

public enum SkipReason {
    NOT_PROTECTABLE,
    PROTECTION_TYPE_UNKNOWN,
    PROTECTION_TYPE_DENIED,
    BLOCK_LOCK_PERMISSION_DENIED,
    ENTITY_LOCK_PERMISSION_DENIED,
    LOCK_EVENT_CANCELLED,
    LOCK_EVENT_UNAVAILABLE,
    LOCK_EVENT_NOT_EVALUATED,
    ACCESS_TYPE_UNKNOWN,
    ACCESS_TYPE_DENIED,
    GROUP_UNKNOWN,
    ACCESS_ALREADY_SET,
    ACCESS_NOT_PRESENT,
    NO_PROTECTION,
    OWNER_MISMATCH,
    EDIT_ACCESS_DENIED,
    WORLDGUARD_DENIED,
    PROTECTION_BLOCK_UNAVAILABLE,
    DUPLICATE_PROTECTION,
    TYPE_ALREADY_SET,
    TRANSFER_TARGET_SAME_AS_OWNER
}
